##### *please correct my horrible spelling*

# Bringing over the data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
FULL_FINRA_df = pd.read_csv("../data/finra_combined_prep.csv")
FULL_CFPB_df = pd.read_csv("../data/cfpb_combined_prep.csv")

In [3]:
FULL_FINRA_df

NFCSID  CENSUSREG  CENSUSDIV  A3  A3Ar_w  A4A_new_w  A5_2015  A8  \
0      2018010001          4          9   2       5          1        5   1   
1      2018010002          3          5   2       2          1        6   5   
2      2018010003          3          7   2       2          1        6   4   
3      2018010004          3          5   2       1          1        6   5   
4      2018010005          4          8   1       2          1        6   3   
...           ...        ...        ...  ..     ...        ...      ...  ..   
27086  2018037087          4          8   2       3          1        2   4   
27087  2018037088          1          1   2       2          2        2   3   
27088  2018037089          1          1   1       2          2        6   2   
27089  2018037090          1          1   2       1          2        6   5   
27090  2018037091          1          1   2       1          2        4   4   

       A7  J41_2  ...  G30_97  G30_98  G30_99  G25_1  G25_4  A6  A41  J1  J3  \
0       4      5  ...       1       0       0      1      3   4   98   1   3   
1       2      5  ...       1       0       0      1      1   1    5   4   3   
2       2      5  ...       0       0       0      1      1   1    3   1   2   
3       2      4  ...       0       1       0      5      3   2    5   8   2   
4       2      3  ...       0       0       0      1      1   1    5   6   3   
...    ..    ...  ...     ...     ...     ...    ...    ...  ..  ...  ..  ..   
27086   2      4  ...       1       0       0      1      1   1    2   7   2   
27087   2     99  ...       1       0       0      1     99   1    2  99  99   
27088   3      4  ...       1       0       0      1      1   2    1   5   2   
27089   1      1  ...       0       0       0      5      4   2    5   5   1   
27090   2      4  ...       1       0       0      1      1   2    5   9   1   

       B2  
0       2  
1       1  
2       2  
3      98  
4       1  
...    ..  
27086   2  
27087  99  
27088   2  
27089   1  
27090   2  

[27091 rows x 33 columns]

In [4]:
FULL_CFPB_df

PUF_ID  PPREG4  PPREG9  PPGENDER  agecat  PPETHM  PPEDUC  PPINCIMP  \
0      10350       4       8         1       8       1       4         7   
1       7740       2       3         1       3       1       2         6   
2      13699       4       9         1       3       2       3         6   
3       7267       3       7         1       3       1       2         8   
4       7375       2       4         1       2       3       2         7   
...      ...     ...     ...       ...     ...     ...     ...       ...   
6389   11220       2       3         2       7       2       5         9   
6390   13118       3       6         1       6       2       2         3   
6391    8709       1       2         2       2       1       5         9   
6392    8515       4       9         1       2       4       2         4   
6393    8516       3       5         1       3       2       5         4   

      PPHHSIZE  FWB1_5  ...  ACT1_2  PRODHAVE_8  PRODUSE_2  PPMARIT  HHEDUC  \
0            1       2  ...       3           0          0        3       4   
1            2       3  ...       3           0          0        3       2   
2            3       3  ...       3           0          0        3       3   
3            1       3  ...      -1           0          0        3      -1   
4            5       3  ...       3           0          1        1       2   
...        ...     ...  ...     ...         ...        ...      ...     ...   
6389         3       3  ...       4           0          0        1       5   
6390         3       5  ...       4           0          0        1       3   
6391         2       3  ...       4           1          0        1       5   
6392         2       5  ...       4           0          0        5       4   
6393         4       3  ...       3           0          0        1       5   

      PAREDUC  HOUSESAT  SWB_1  MANAGE1_2  AUTOMATED_2  
0           4         4      5          4            0  
1           2         3      6          4            0  
2           3         3      4          3            1  
3           2        -1      6          4           -1  
4           2         3      4          3            1  
...       ...       ...    ...        ...          ...  
6389        1         4      6          3            1  
6390        3         4      7          4            7  
6391        4         3      5          5            1  
6392        2         3      5          3            7  
6393        5         3      4          2            0  

[6394 rows x 30 columns]

## getting rid of the 'Maybe' Columns (for now)

In [5]:
maybeFIN = ['A6','A41','J1','J3','B2']
FINRA_df = FULL_FINRA_df.drop(columns = maybeFIN)

In [6]:
FINRA_df

NFCSID  CENSUSREG  CENSUSDIV  A3  A3Ar_w  A4A_new_w  A5_2015  A8  \
0      2018010001          4          9   2       5          1        5   1   
1      2018010002          3          5   2       2          1        6   5   
2      2018010003          3          7   2       2          1        6   4   
3      2018010004          3          5   2       1          1        6   5   
4      2018010005          4          8   1       2          1        6   3   
...           ...        ...        ...  ..     ...        ...      ...  ..   
27086  2018037087          4          8   2       3          1        2   4   
27087  2018037088          1          1   2       2          2        2   3   
27088  2018037089          1          1   1       2          2        6   2   
27089  2018037090          1          1   2       1          2        6   5   
27090  2018037091          1          1   2       1          2        4   4   

       A7  J41_2  ...  G30_1  G30_2  G30_3  G30_4  G30_5  G30_97  G30_98  \
0       4      5  ...      0      0      0      0      0       1       0   
1       2      5  ...      0      0      0      0      0       1       0   
2       2      5  ...      1      0      0      0      0       0       0   
3       2      4  ...      0      0      0      0      0       0       1   
4       2      3  ...      1      0      0      0      0       0       0   
...    ..    ...  ...    ...    ...    ...    ...    ...     ...     ...   
27086   2      4  ...      0      0      0      0      0       1       0   
27087   2     99  ...      0      0      0      0      0       1       0   
27088   3      4  ...      0      0      0      0      0       1       0   
27089   1      1  ...      1      0      0      0      0       0       0   
27090   2      4  ...      0      0      0      0      0       1       0   

       G30_99  G25_1  G25_4  
0           0      1      3  
1           0      1      1  
2           0      1      1  
3           0      5      3  
4           0      1      1  
...       ...    ...    ...  
27086       0      1      1  
27087       0      1     99  
27088       0      1      1  
27089       0      5      4  
27090       0      1      1  

[27091 rows x 28 columns]

In [7]:
FINRA_df.columns

Index(['NFCSID', 'CENSUSREG', 'CENSUSDIV', 'A3', 'A3Ar_w', 'A4A_new_w',
       'A5_2015', 'A8', 'A7', 'J41_2', 'C1_2012', 'C4_2012', 'EA_1', 'A11',
       'A9', 'J4', 'J20', 'J43', 'G30_1', 'G30_2', 'G30_3', 'G30_4', 'G30_5',
       'G30_97', 'G30_98', 'G30_99', 'G25_1', 'G25_4'],
      dtype='object')

In [8]:
maybeCF = ['PPMARIT', 'HHEDUC', 'PAREDUC', 'HOUSESAT', 'SWB_1', 'MANAGE1_2', 'AUTOMATED_2']
CFPB_df = FULL_CFPB_df.drop(columns = maybeCF)
CFPB_df

PUF_ID  PPREG4  PPREG9  PPGENDER  agecat  PPETHM  PPEDUC  PPINCIMP  \
0      10350       4       8         1       8       1       4         7   
1       7740       2       3         1       3       1       2         6   
2      13699       4       9         1       3       2       3         6   
3       7267       3       7         1       3       1       2         8   
4       7375       2       4         1       2       3       2         7   
...      ...     ...     ...       ...     ...     ...     ...       ...   
6389   11220       2       3         2       7       2       5         9   
6390   13118       3       6         1       6       2       2         3   
6391    8709       1       2         2       2       1       5         9   
6392    8515       4       9         1       2       4       2         4   
6393    8516       3       5         1       3       2       5         4   

      PPHHSIZE  FWB1_5  ...  KIDS_1  KIDS_2  KIDS_3  KIDS_4  EMPLOY  ENDSMEET  \
0            1       2  ...       0       0       0       0       8         2   
1            2       3  ...       0       0       0       0       2         2   
2            3       3  ...       0       0       0       1       2         1   
3            1       3  ...       0       0       0       0      99        -1   
4            5       3  ...       0       0       0       0       2         2   
...        ...     ...  ...     ...     ...     ...     ...     ...       ...   
6389         3       3  ...       0       0       1       0       8         2   
6390         3       5  ...       1       0       2       0       8         2   
6391         2       3  ...       0       0       0       0       2         1   
6392         2       5  ...       2       0       0       0       3         2   
6393         4       3  ...       0       2       0       0       2         3   

      FWB1_1  ACT1_2  PRODHAVE_8  PRODUSE_2  
0          3       3           0          0  
1          2       3           0          0  
2          3       3           0          0  
3          3      -1           0          0  
4          3       3           0          1  
...      ...     ...         ...        ...  
6389       3       4           0          0  
6390       3       4           0          0  
6391       3       4           1          0  
6392       2       4           0          0  
6393       3       3           0          0  

[6394 rows x 23 columns]

In [9]:
CFPB_df.columns

Index(['PUF_ID', 'PPREG4', 'PPREG9', 'PPGENDER', 'agecat', 'PPETHM', 'PPEDUC',
       'PPINCIMP', 'PPHHSIZE', 'FWB1_5', 'AUTOMATED_1', 'HOUSING',
       'KIDS_NoChildren', 'KIDS_1', 'KIDS_2', 'KIDS_3', 'KIDS_4', 'EMPLOY',
       'ENDSMEET', 'FWB1_1', 'ACT1_2', 'PRODHAVE_8', 'PRODUSE_2'],
      dtype='object')

# -------------------Column explanations-----------------------

## Columns we have ready

### ```NFISID``` and ```PUF_ID```

Since they could still be useful in identifing the different individuals, i'll keep it in

### ```Census Region``` and ```Census Division```

 They look perfect to me! we can combine them as is.

### ```Gender```

Also looks perfect to me!

### ```Age group```

The first four levels (up to age 54) are the same in both datasets, but its differs afterthat. We will need to adjust the last levels of each dataset before mergins

In [10]:
#code here adjust FINRA data 
FINRA_df.loc[FINRA_df['A3Ar_w'] > 4, 'A3Ar_w'] = 5
CFPB_df.loc[CFPB_df['agecat'] > 4, 'agecat'] = 5

In [11]:
FINRA_df['A3Ar_w'].unique()

array([5, 2, 1, 4, 3])

In [12]:
CFPB_df['agecat'].unique()

array([5, 3, 2, 4, 1])

### ```Race/Ethnicity``` and ```Race```

As mentioned in our previous meetings, the FINRA dataset has race seperated between white and non-white. We will need to adjust for that

In [13]:
#PPETHM & A4A_new_w

#Change values in CFPB
CFPB_df.loc[CFPB_df['PPETHM'] > 1, 'PPETHM'] = 2
#race_map = {
#    "Race/Ethnicity":{
#      "White, Non-Hispanic": "White",
#      "Black, Non-Hispanic": "Non-White",
#      "Other, Non-Hispanic": "Non-White",
#      "Hispanic": "Non-White"
#    },
#}

CFPB_df['PPETHM'].unique()

array([1, 2])

### ```Education (Highest Degree)```

Present in both! FINRA dataset needs to be adjusted to fit to CFPB dataset (PPEDUC & A5_2015)

In [14]:
FINRA_df['A5_2015'].unique()

array([5, 6, 3, 2, 7, 4, 1])

In [15]:
education_map = {
    "A5_2015":{
        1: 1,
        2: 2,
        3: 2,
        4: 3,
        5: 3,
        6: 4,
        7: 5
    }
}
FINRA_df = FINRA_df.replace(education_map)
FINRA_df['A5_2015'].unique()

array([3, 4, 2, 5, 1])

### ```Household Income```

Present in both! Both need to be adjusted to fit one another

In [16]:
FINRA_df['A8'].unique()

array([1, 5, 4, 3, 6, 2, 7, 8])

In [17]:
CFPB_df['PPINCIMP'].unique()

array([7, 6, 8, 4, 3, 9, 2, 1, 5])

In [18]:
#PPINCIMP A8
#Fix CFPB
houseincome_map_finra = {
    "A8":{
        1: 1,
        2: 1,
        3: 1,
        4: 1,
        5: 1,
        6: 2,
        7: 3,
        8: 4
    }
}
houseincome_map_cfpb = {
    "PPINCIMP":{
        1: 1,
        2: 1,
        3: 1,
        4: 1,
        5: 1,
        6: 1,
        7: 2,
        8: 3,
        9: 4
    }
}
CFPB_df = CFPB_df.replace(houseincome_map_cfpb)
CFPB_df['PPINCIMP'].unique()

array([2, 1, 3, 4])

In [19]:
FINRA_df = FINRA_df.replace(houseincome_map_finra)
FINRA_df['A8'].unique()

array([1, 2, 3, 4])

### ```Household Size``` (Did we agree to use it? ) (come back to monday)

Okay its a bit of a stretch but I think ```A7``` in the FINRA dataset can match with the CFPB column. I say we try it, but if it feels off we can just not include it

In [20]:
#making max value to 3+
housesize_map_cfpb = {
    "PPHHSIZE":{
        1: 1,
        2: 2,
        3: 3,
        4: 3,
        5: 3
    }
}
housesize_map_finra = {
    "A7":{
        1: 1,
        2: 2,
        3: 3,
        4: 3,
        5: 3
    }
}
CFPB_df = CFPB_df.replace(housesize_map_cfpb)
FINRA_df = FINRA_df.replace(housesize_map_finra)
CFPB_df['PPHHSIZE'].unique()

array([1, 2, 3])

In [21]:
FINRA_df['A7'].unique()

array([3, 2, 1])

### ```I am just getting by financially```

`J41_2` in the FINRA dataset and `FWB1_5` in the CFPB dataset are almost exactly the same! Horray!

### ```Retirement Plan```

In [22]:
#Combine c1 and c4,
#AUTOMATED_1
#new column name 'A Retirement Savings Account'
check_mapA = {
    'C1_2012': {
        1 : 1,
        2 : 0,
        98: 25,
        99: 99
    }
}
check_mapB = {
    'C4_2012': {
        1 : 1,
        2 : 0,
        98: 25,
        99: 99
    }
}
FINRA_df = FINRA_df.replace(check_mapA)
FINRA_df = FINRA_df.replace(check_mapB)
FINRA_df['C1_2012'] = FINRA_df['C1_2012'] + FINRA_df['C4_2012']
FINRA_df['C1_2012']

0         1
1         2
2         1
3        50
4         1
         ..
27086     1
27087     0
27088     0
27089     1
27090    25
Name: C1_2012, Length: 27091, dtype: int64

In [23]:
FINRA_df['C1_2012'].unique()

array([  1,   2,  50,   0,  26,  25, 198, 124,  99, 100])

In [24]:
final_check_map = {
    'C1_2012':{
        0: 0,
        1: 1,
        2: 1,
        25: 98,
        26: 1,
        50: 98,
        99: 99,
        100: 1,
        124: 99,
        198: 99,
    }
}
FINRA_df = FINRA_df.replace(final_check_map)
FINRA_df['C1_2012'].unique()

array([ 1, 98,  0, 99])

In [25]:
FINRA_df = FINRA_df.drop(columns = ['C4_2012'])

### ```Housing```

In [26]:
#adjust values of HOUSING to EA_1
ownhome_map = {
    'HOUSING': {
        1: 1,
        2 : 2,
        3 : 2,
        -1 : 99
    }
}
CFPB_df = CFPB_df.replace(ownhome_map)
CFPB_df['HOUSING'].unique()
#CFPB_MAPPED['Do you currently own your home?'].unique()

array([ 1, 99,  2])

### ```Number of Dependents``` (talk to group about it)

In [27]:
#I believe that we're using the KIDS_NoChildren, KIDS_1, etc, columns with A11

#KIDS_2 has a random invalid response lol
CFPB_df['KIDS_2'] = CFPB_df['KIDS_2'].replace(-3, 0)

CFPB_df['number of dependents'] = CFPB_df['KIDS_1'].replace(-1, 0) + CFPB_df['KIDS_2'].replace(-1, 0) + CFPB_df['KIDS_3'].replace(-1, 0) + CFPB_df['KIDS_4'].replace(-1, 0)   
CFPB_df.loc[CFPB_df['number of dependents'] > 3, 'number of dependents'] = 4
CFPB_df['number of dependents'] = np.where((CFPB_df['KIDS_1'] == -1) & (CFPB_df['KIDS_2'] == -1) & (CFPB_df['KIDS_3'] == -1) & (CFPB_df['KIDS_4'] == -1), 99, CFPB_df['number of dependents'])

#df['First Season'] = np.where(df['First Season'] > 1990, 1, df['First Season'])
#the above line is for reference



#Kids_valuemap = {
#    'number of dependents':{
#        0: 5,
#        1: 
#        2:
#        3:
#        4:
#    }
#}

In [28]:
CFPB_df['number of dependents'] = np.where(CFPB_df['KIDS_NoChildren'] == 1, 5, CFPB_df['number of dependents'])
CFPB_df['number of dependents'] = CFPB_df['number of dependents'].replace(0, 6)
CFPB_df['KIDS_1'] = CFPB_df['number of dependents']

In [29]:
CFPB_df = CFPB_df.drop(columns = ['KIDS_NoChildren','KIDS_2', 'KIDS_3', 'KIDS_4', 'number of dependents'])

In [30]:
CFPB_df['KIDS_1'].unique()

array([6, 5, 1, 4, 2, 3])

### ```Employment Status```

Perfect

### ```How Difficult is it to Cover Expenses?```

 `J4` in the FINRA dataset asks `'In a typical month, how difficult is it for you to cover your expenses and pay all your bills?'`. `ENDSMEET` asks `'Difficulty of covering monthly expenses and bills'`

In [31]:
#j4 and endsmeet
#reverse numbers for ENDSMEET

cover_expenses_map = {
    'ENDSMEET': {
        1: 3,
        2: 2,
        3: 1
    }
}

CFPB_df = CFPB_df.replace(cover_expenses_map)
CFPB_df['ENDSMEET'].unique()

array([ 2,  3, -1,  1])

### ```How Confident are you that You Could Come Up with $2000 Dollars Unexpectedly``` (go over again :/)

```J20``` has this question in the FINRA dataset, and I think its a good way to see how well prepared people are financially. There is a column in the CFPB dataset that has something similar, `FWB1_1`, which says `'I could handle a major unexpected expense'`. However, I think its fine if we leave this as a strech goal for now.

In [32]:
#j20 and FWB1_1
unex_finra = {
    'J20':{
        1:1,
        2:2,
        3:2,
        4:3
    }
}
unex_cfpb = {
    'FWB1_1':{
        1:1,
        2:2,
        3:2,
        4:2,
        5:3
    }
}
CFPB_df = CFPB_df.replace(unex_cfpb)
CFPB_df['FWB1_1'].unique()

array([ 2,  3,  1, -4, -1])

In [33]:
FINRA_df = FINRA_df.replace(unex_finra)
FINRA_df['J20'].unique()

array([ 3,  1,  2, 99, 98])

### `I follow-through on financial goals I set for myself.`

In [34]:
#ACT1_2, J43
financial_goals_map = {
    'ACT1_2':{
        -1: 99,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 4
    }
}
CFPB_df = CFPB_df.replace(financial_goals_map)
CFPB_df['ACT1_2'].unique()

array([ 3, 99,  4,  1,  2])

### `Student/Education Loan (for yourself or someone else)`

The CFPB column `PRODHAVE_8` does have something similar in the `G30` columns in FINRA, which as if you have student loans from youself, your spouse, your children, grandchildren, or other individual. Its a bit messy but should we decide to bring it in, it should be easy to clean up the mess.

In [35]:
FINRA_df['G30_1'] = FINRA_df['G30_1']+FINRA_df['G30_2']+FINRA_df['G30_3']+FINRA_df['G30_4']+FINRA_df['G30_5']

FINRA_df.loc[FINRA_df['G30_1'] > 1, 'G30_1'] = 1
FINRA_df['G30_1'].unique()

array([0, 1])

In [36]:
FINRA_df.loc[FINRA_df['G30_98'] == 1, 'G30_1'] = 98
FINRA_df.loc[FINRA_df['G30_99'] == 1, 'G30_1'] = 99
FINRA_df['G30_1'].unique()


array([ 0,  1, 98, 99])

In [37]:
FINRA_df = FINRA_df.drop(columns = ['G30_2', 'G30_3', 'G30_4', 'G30_5',
       'G30_97', 'G30_98', 'G30_99'])

### `Used pawn loan or auto title loan`

The column in CFPB `PRODUSE_2` has something similar named `G25_1` in the FINRA dataset. Specifically, they both mention auto title loans. I'm not sure how important this is, and considering that the FINRA one makes no mention of the pawn loan, I think its safe to delete this column.

In [38]:
FINRA_df['G25_1'] = FINRA_df['G25_1'].replace([98,99], 1) + FINRA_df['G25_4'].replace([98,99], 1)
FINRA_df.loc[FINRA_df['G25_1'] > 2, 'G25_1'] = 3
pawn_auto_map = {
    'G25_1':{
        2: 0,
        3:1
    }
}
FINRA_df = FINRA_df.replace(pawn_auto_map)

In [39]:
FINRA_df['G25_1'].unique()

array([1, 0])

In [40]:
FINRA_df = FINRA_df.drop(columns = ['G25_4'])

In [41]:
FINRA_df.columns

Index(['NFCSID', 'CENSUSREG', 'CENSUSDIV', 'A3', 'A3Ar_w', 'A4A_new_w',
       'A5_2015', 'A8', 'A7', 'J41_2', 'C1_2012', 'EA_1', 'A11', 'A9', 'J4',
       'J20', 'J43', 'G30_1', 'G25_1'],
      dtype='object')

In [42]:
CFPB_df.columns

Index(['PUF_ID', 'PPREG4', 'PPREG9', 'PPGENDER', 'agecat', 'PPETHM', 'PPEDUC',
       'PPINCIMP', 'PPHHSIZE', 'FWB1_5', 'AUTOMATED_1', 'HOUSING', 'KIDS_1',
       'EMPLOY', 'ENDSMEET', 'FWB1_1', 'ACT1_2', 'PRODHAVE_8', 'PRODUSE_2'],
      dtype='object')

### renaming and combining

In [43]:
renaming = [
    'ID',
    'PPREG4',
    'PPREG9',
    'PPGENDER',
    'agecat',
    'PPETHM',
    'PPEDUC',
    'PPINCIMP',
    'PPHHSIZE',
    'FWB1_5',
    'AUTOMATED_1',
    'HOUSING',
    'KIDS_1',
    'EMPLOY',
    'ENDSMEET',
    'FWB1_1',
    'ACT1_2',
    'PRODHAVE_8',
    'PRODUSE_2',
]
FINRA_df.columns = renaming
FINRA_df.columns

Index(['ID', 'PPREG4', 'PPREG9', 'PPGENDER', 'agecat', 'PPETHM', 'PPEDUC',
       'PPINCIMP', 'PPHHSIZE', 'FWB1_5', 'AUTOMATED_1', 'HOUSING', 'KIDS_1',
       'EMPLOY', 'ENDSMEET', 'FWB1_1', 'ACT1_2', 'PRODHAVE_8', 'PRODUSE_2'],
      dtype='object')

In [44]:
CFPB_df = CFPB_df.rename(columns={'PUF_ID': 'ID'})

In [45]:
combined_df = pd.concat([FINRA_df, CFPB_df])
combined_df

ID  PPREG4  PPREG9  PPGENDER  agecat  PPETHM  PPEDUC  PPINCIMP  \
0     2018010001       4       9         2       5       1       3         1   
1     2018010002       3       5         2       2       1       4         1   
2     2018010003       3       7         2       2       1       4         1   
3     2018010004       3       5         2       1       1       4         1   
4     2018010005       4       8         1       2       1       4         1   
...          ...     ...     ...       ...     ...     ...     ...       ...   
6389       11220       2       3         2       5       2       5         4   
6390       13118       3       6         1       5       2       2         1   
6391        8709       1       2         2       2       1       5         4   
6392        8515       4       9         1       2       2       2         1   
6393        8516       3       5         1       3       2       5         1   

      PPHHSIZE  FWB1_5  AUTOMATED_1  HOUSING  KIDS_1  EMPLOY  ENDSMEET  \
0            3       5            1        1       5       6         1   
1            2       5            1        2       6       2         2   
2            2       5            1        2       1       2         1   
3            2       4           98       98       2       2         3   
4            2       3            1        2       6       2         3   
...        ...     ...          ...      ...     ...     ...       ...   
6389         3       3            0        1       1       8         2   
6390         3       5            7        1       3       8         2   
6391         2       3            1        2       5       2         3   
6392         2       5            7        2       2       3         2   
6393         3       3            0        2       2       2         1   

      FWB1_1  ACT1_2  PRODHAVE_8  PRODUSE_2  
0          3       2           0          1  
1          1       2           0          0  
2          3       1           1          0  
3          2       3          98          1  
4          1       3           1          0  
...      ...     ...         ...        ...  
6389       2       4           0          0  
6390       2       4           0          0  
6391       2       4           1          0  
6392       2       4           0          0  
6393       2       3           0          0  

[33485 rows x 19 columns]

In [46]:
col_map = {
    'PPREG4':'Census Region',
    'PPREG9':'Census Division',
    'PPGENDER':'Gender',
    'agecat':'Age Group',
    'PPETHM':'Race/Ethnicity',
    'PPEDUC':'Education (Highest Degree)',
    'PPINCIMP':'Household Income',
    'PPHHSIZE':'Household Size',
    'FWB1_5':'I am just getting by financially',
    'AUTOMATED_1':'A Retirement Savings Account',
    'HOUSING':'Do you currently own your home?',
    'KIDS_1':'How many children do you have who are financially dependent on you',
    'EMPLOY':'Primary or only employment status',
    'ENDSMEET':'How Difficult is it to Cover Expenses?',
    'FWB1_1':'I could handle a major unexpected expense',
    'ACT1_2':'I follow-through on financial goals I set for myself.',
    'PRODHAVE_8':'Student/Education Loan (for yourself or someone else)',
    'PRODUSE_2':'Used pawn loan or auto title loan'
}

combined_df = combined_df.rename(columns=col_map)
combined_df = combined_df.replace(-1, 99)
combined_df

ID  Census Region  Census Division  Gender  Age Group  \
0     2018010001              4                9       2          5   
1     2018010002              3                5       2          2   
2     2018010003              3                7       2          2   
3     2018010004              3                5       2          1   
4     2018010005              4                8       1          2   
...          ...            ...              ...     ...        ...   
6389       11220              2                3       2          5   
6390       13118              3                6       1          5   
6391        8709              1                2       2          2   
6392        8515              4                9       1          2   
6393        8516              3                5       1          3   

      Race/Ethnicity  Education (Highest Degree)  Household Income  \
0                  1                           3                 1   
1                  1                           4                 1   
2                  1                           4                 1   
3                  1                           4                 1   
4                  1                           4                 1   
...              ...                         ...               ...   
6389               2                           5                 4   
6390               2                           2                 1   
6391               1                           5                 4   
6392               2                           2                 1   
6393               2                           5                 1   

      Household Size  I am just getting by financially  \
0                  3                                 5   
1                  2                                 5   
2                  2                                 5   
3                  2                                 4   
4                  2                                 3   
...              ...                               ...   
6389               3                                 3   
6390               3                                 5   
6391               2                                 3   
6392               2                                 5   
6393               3                                 3   

      A Retirement Savings Account  Do you currently own your home?  \
0                                1                                1   
1                                1                                2   
2                                1                                2   
3                               98                               98   
4                                1                                2   
...                            ...                              ...   
6389                             0                                1   
6390                             7                                1   
6391                             1                                2   
6392                             7                                2   
6393                             0                                2   

      How many children do you have who are financially dependent on you  \
0                                                     5                    
1                                                     6                    
2                                                     1                    
3                                                     2                    
4                                                     6                    
...                                                 ...                    
6389                                                  1                    
6390                                                  3                    
6391                                                  5                    
6392      

In [47]:
for x in combined_df.columns:
    print(x)
    print(combined_df[x].unique())
    print()

ID
[2018010001 2018010002 2018010003 ...       8709       8515       8516]

Census Region
[4 3 2 1]

Census Division
[9 5 7 8 4 1 2 3 6]

Gender
[2 1]

Age Group
[5 2 1 4 3]

Race/Ethnicity
[1 2]

Education (Highest Degree)
[3 4 2 5 1]

Household Income
[1 2 3 4]

Household Size
[3 2 1]

I am just getting by financially
[ 5  4  3  2  1 98 99 -4]

A Retirement Savings Account
[ 1 98  0 99  7]

Do you currently own your home?
[ 1  2 98 99]

How many children do you have who are financially dependent on you
[5 6 1 2 4 3]

Primary or only employment status
[ 6  2  3  8  4  1  7  5 99]

How Difficult is it to Cover Expenses?
[ 1  2  3 99 98]

I could handle a major unexpected expense
[ 3  1  2 99 98 -4]

I follow-through on financial goals I set for myself.
[ 2  1  3 98  4 99]

Student/Education Loan (for yourself or someone else)
[ 0  1 98 99]

Used pawn loan or auto title loan
[1 0]



In [48]:
column_values = combined_df.drop(columns = ['ID']).values.ravel()
unique_values =  pd.unique(column_values)
unique_values

array([ 4,  9,  2,  5,  1,  3,  6,  0,  7, 98,  8, 99, -4])

In [49]:
combined_df[(combined_df == -4).any(axis=1)]

ID  Census Region  Census Division  Gender  Age Group  Race/Ethnicity  \
884  12173              3                5       2          5               1   

     Education (Highest Degree)  Household Income  Household Size  \
884                           3                 3               1   

     I am just getting by financially  A Retirement Savings Account  \
884                                -4                             1   

     Do you currently own your home?  \
884                                1   

     How many children do you have who are financially dependent on you  \
884                                                  5                    

     Primary or only employment status  \
884                                  2   

     How Difficult is it to Cover Expenses?  \
884                                       2   

     I could handle a major unexpected expense  \
884                                         -4   

     I follow-through on financial goals I set for myself.  \
884                                                  3       

     Student/Education Loan (for yourself or someone else)  \
884                                                  0       

     Used pawn loan or auto title loan  
884                                  0

### VALUE MAP

In [50]:
#Value map
vmap = {
    "Census Region":{
        1: "Northeast",
        2: "Midwest",
        3: "South",
        4: "West"
    },
    "Census Division":{
        1: "New England",
        2: "Mid-Atlantic",
        3: "East-North Central",
        4: "West-North Central",
        5: "South Atlantic",
        6: "East-South Central",
        7: "West-South Central",
        8: "Mountain",
        9: "Pacific"
    }, 
    "Gender":{
        1: "Male",
        2: "Female"
    },
    "Age Group":{
        1: "18-24",
        2: "25-34",
        3: "35-44",
        4: "45-54",
        5: "55+"
    },
    "Race/Ethnicity":{
        1: "White",
        2: "Non-White"
    },
    "Education (Highest Degree)":{
        1: "Less than high school",
        2: "High school degree/GED",
        3: "Some college/Associate",
        4: "Bachelors degree",
        5: "Graduate/professional degree"
    },
    "Household Income":{
        1: "Less than $75,000",
        2: "$75,000 to $99,999",
        3: "$100,000 to $149,999",
        4: "$150,000 or more"
    },
    "Household Size":{
        1: "1",
        2: "2",
        3: "3+",
    },
    "I am just getting by financially":{
        1: "Not at all",
        2: "Very little",
        3: "Somewhat",
        4: "Very well",
        5: "Completely",
    },
    'A Retirement Savings Account':{
        0:'No',
        1:'Yes',
        2:'Yes',
        7:'No',
    },
    'Do you currently own your home?':{
        1:'Yes',
        2:'No',
    },
    'How many children do you have who are financially dependent on you':{
        1: '1',
        2: '2',
        3: '3',
        4: '4+',
        5: 'No financially dependent children',
        6: 'Do not have any children',
    },
    'Primary or only employment status':{
        1: "Self-Employed",
        2: "Full time worker",
        3: "Part time worker",
        4: "Homemaker",
        5: "Full time student",
        6: "Permanently sick, disabled, or unable to work",
        7: "Unemployed or temporarily laid off",
        8: "Retired",
    },
    'How Difficult is it to Cover Expenses?': {
        1: 'Very Difficult',
        2: 'Somewhat difficult',
        3: 'Not difficult at all'
    },
    'I could handle a major unexpected expense':{
        1:'Not at all',
        2:'Somewhat',
        3:'Completely'
    },
    'I follow-through on financial goals I set for myself.':{
        1: 'Not at all confident',
        2: 'Not very confident',
        3: 'Somewhat confident',
        4: 'Very confident',
    },
    'Student/Education Loan (for yourself or someone else)':{
        0: 'No',
        1: 'Yes'
    },
    'Used pawn loan or auto title loan':{
        0: 'No',
        1: 'Yes'
    }
} 

combined_df = combined_df.replace(vmap)

In [51]:
combined_df

ID Census Region     Census Division  Gender Age Group  \
0     2018010001          West             Pacific  Female       55+   
1     2018010002         South      South Atlantic  Female     25-34   
2     2018010003         South  West-South Central  Female     25-34   
3     2018010004         South      South Atlantic  Female     18-24   
4     2018010005          West            Mountain    Male     25-34   
...          ...           ...                 ...     ...       ...   
6389       11220       Midwest  East-North Central  Female       55+   
6390       13118         South  East-South Central    Male       55+   
6391        8709     Northeast        Mid-Atlantic  Female     25-34   
6392        8515          West             Pacific    Male     25-34   
6393        8516         South      South Atlantic    Male     35-44   

     Race/Ethnicity    Education (Highest Degree)   Household Income  \
0             White        Some college/Associate  Less than $75,000   
1             White              Bachelors degree  Less than $75,000   
2             White              Bachelors degree  Less than $75,000   
3             White              Bachelors degree  Less than $75,000   
4             White              Bachelors degree  Less than $75,000   
...             ...                           ...                ...   
6389      Non-White  Graduate/professional degree   $150,000 or more   
6390      Non-White        High school degree/GED  Less than $75,000   
6391          White  Graduate/professional degree   $150,000 or more   
6392      Non-White        High school degree/GED  Less than $75,000   
6393      Non-White  Graduate/professional degree  Less than $75,000   

     Household Size I am just getting by financially  \
0                3+                       Completely   
1                 2                       Completely   
2                 2                       Completely   
3                 2                        Very well   
4                 2                         Somewhat   
...             ...                              ...   
6389             3+                         Somewhat   
6390             3+                       Completely   
6391              2                         Somewhat   
6392              2                       Completely   
6393             3+                         Somewhat   

     A Retirement Savings Account Do you currently own your home?  \
0                             Yes                             Yes   
1                             Yes                              No   
2                             Yes                              No   
3                              98                              98   
4                             Yes                              No   
...                           ...                             ...   
6389                           No                             Yes   
6390                           No                             Yes   
6391                          Yes                              No   
6392                           No                              No   
6393                           No                              No   

     How many children do you have who are financially dependent on you  \
0                     No financially dependent children                   
1                              Do not have any children                   
2                                                     1                   
3                                                     2                   
4                              Do not have any children                   
...                                                 ...                   
6389                                                  1                   
6390                                                  3                   
6391                  No financially dependent children                   
6392                            

### ```Marital Status``` (MAYBE)

There is a column in the orignal dataset of CFPB that wasn't brought over. It could be interesting how marriage and a family could affect someones financial success regardless in spite of the financial education they might have recieved. For now we can drop the marital status column from the FINRA dataset and we can look consider it another time

In [52]:
# PPMARIT & A6

### ```Highest Degree Completed in Household``` (MAYBE)

This one I think is interesting because although an individual might not an advanced education, maybe their spouse or partner has and therefore they make better decisions. There is also a column in the CFPB dataset that we can grab (HHEDUC, PAREDUC). However, This might be more of a strech goal. We can get rid of it for now but we can consider it for a later time

In [53]:
#drop colum from FINRA (A41)

#Code to bring in CFPB column(HHEDUC, PAREDUC)(strech goal)(read note in Employment Status)

### `How Satisfied are you Financially?` (MAYBE)

This one is a bit tricky. In FINRA the question `J1` states `'Overall, thinking of your assets, debts and savings, how satisfied are you with your current personal financial condition?'`, with a scale from 1 to 10. In the CFPB survey there are two sections, one being `SWB_1` which states `'I am satisfied with my life'` with a scale from 1 to 7, and `HOUSESAT` which states '`How satisfied are you with the place you live currently?'` with a scale from 1 to 4.<br>
I think this is an important question because we could find that individuals that are content might not make much progress even if they had financial education. I think `SWB_1` is probably the better fit, but it will be hard to get the scaling correct. For now, we can drop `J1` but I suggest we return to it at a later time

In [54]:
#code to drop J1

#Code to bring in CFPB column (HOUSESAT, SWB_1)(strech goal)(read note in Employment Status)

### ```Do You Spend More Than, Less Than, or Equal What You Make?``` ------- IMPORTANT ------ (MAYBE)

This column, `J3`, is another column that I really want to save. Its the closest thing we have to see how much they spend compared to how much they make. However, I didn't find anything in the CFPB dataset that matched this. If we someone knows how we can combine the two with regards to this column, please let me know! (I think `MANAGE1_2` from the CFPB dataset was close, what do you think?)

In [55]:
#code to drop J3

### `A Non-Retirement Savings Account` (MAYBE)

the column `AUTOMATED_2` in the CFPB column has its counterpart in column `B2` of the FINRA dataset, which states `'Do you [Does your household] have a savings account, money marketaccount, or CDs?'`. The CFPB column has three values, but tbh two of them are pretty much the same. Therefore using the two of them should be almost no problem

In [56]:
#code to bring in B2

#code to change value names and get AUTOMATED_2 values in line with B2